# Generated by Django 2.0.7 on 2018-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.URLField(null=True),
        ),
    ]
