# Generated by Django 2.0.7 on 2018-07-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_first_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='originalUrl',
            new_name='original_url',
        ),
        migrations.AddField(
            model_name='post',
            name='first_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_raw',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
